# Generated by Django 5.0.4 on 2024-05-03 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Students', to='courseapp.course'),
        ),
    ]
