# Generated by Django 5.0.4 on 2024-05-13 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0005_subject_student_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
